"""
SCons Platform B
"""

Import('arch_env')
Import('arch')
Import('platform')

print(f'Loading SConscript Arch={arch} Platform={platform}')

platform_env=arch_env.Clone(CPPDEFINES=[ {'PLATFORM' : platform}, '$CPPDEFINES'])
		            #Platform specific stuff here

platform_env.Program(f'#/build/{arch}-{platform}/hello',
		     f'#/src/hello.cpp')
