"""
SCons Architecture
"""

Import('env')
Import('arch')

arch_env = env.Clone(CPPDEFINES={'ARCH':arch})

platforms = ['platform_a', 'platform_b']

# If I just have 1 Everything is fine!
# platforms = ['platform_a']

for platform in platforms:
    Export('arch_env')
    Export('arch')
    Export('platform')
    SConscript(f'#/{arch}/{platform}/SConscript',
               variant_dir=f'#/build/{arch}-{platform}',
               duplicate=False)
